/**
 * @fileoverview Study of EEW project definition
 * Linguistic study of the Evolutionary Ecology of Words model
 */

import { Retex } from '../dataTypes';
import { UNIVERSAL_LANG } from '../i18n';
import { getSkill } from '../skillsIndex';
import { projectsImages, documents } from '../index';

export const studyOfEew: Retex = {
  title: {
    fr: "Étude de EEW",
    en: "Study of EEW",
  },
  date: new Date(2025, 5),
  tools: [
    getSkill('Python'),
    getSkill('Matplotlib'),
    getSkill('Latex'),
  ],
  description: {
    fr:
    "Cette étude de cas explore les propriétés de dérivation sémantique via le modèle EEW selon le langage employé.",
    en:
    "This case study explores the properties of semantic derivation through the EEW model according to the language used."
  },
  specs: {
    fr:
    "J'ai contribué à l'étude du modèle <strong>Evolutionary Ecology of Words</strong> (EEW), une expérience de <strong>vie artificielle</strong> \
    où <strong>des écosystèmes de mots</strong>, générés par un LLM, entrent en compétition pour dominer l'environnement. Mon rôle a \
    été de mener une étude linguistique analysant <strong>l'impact de la langue sur les dynamiques de \
    dérivation sémantique</strong>. J'ai mis en évidence un biais linguistique : la langue initiale influence \
    fortement la créativité du LLM, avec des comportements distincts selon les idiomes. En combinant \
    plusieurs langues dans une même expérience, j'ai démontré <strong>une émergence accrue de nouveauté</strong>. \
    Un résultat pertinent pour <strong>la recherche sur l'open-endedness</strong>, que j'ai eu la chance de présenter \
    lors de <strong>la conférence JSAI</strong> à Osaka. Ma participation s'inscrit dans le travail de recherche du <strong>Pr. Reiji Suzuki</strong>.",
    en:
    "I contributed to the study of the <strong>Evolutionary Ecology of Words</strong> (EEW) model, an experiment in <strong>artificial life</strong> \
    where <strong>word ecosystems</strong>, generated by an LLM, compete to dominate the environment. My role was \
    to conduct a linguistic study analyzing <strong>the impact of language on the dynamics of semantic derivation</strong>. \
    I highlighted a linguistic bias: the initial language strongly influences the creativity of the LLM, with distinct behaviors \
    depending on the idioms. By combining multiple languages in a single experiment, I demonstrated <strong>an increased emergence of novelty</strong>. \
    A relevant result for <strong>research on open-endedness</strong>, which I had the chance to present at <strong>the JSAI conference</strong> in Osaka. \
    My participation is part of the research work of <strong>Pr. Reiji Suzuki</strong>."
  },
  notions: {
    fr: ["Étude comportementale sur des LLM", "Analyse de données et interprétation", "Présentation de la recherche"],
    en: ["Behavioral study on LLMs", "Data analysis and interpretation", "Research presentation"],
  },
  tags: {
    fr: ["ALife", "Data", "Recherche", "IA", "Professionnel", "Sémantique", "Vie artificielle"],
    en: ["ALife", "Data", "Research", "AI", "Professional", "Semantic", "Artificial life"],
    [UNIVERSAL_LANG]: ["LLM"]
  },
  img: [
    projectsImages.eew_basic_visuals,
    projectsImages.eew_algo,
    projectsImages.eew_lang_behaviors,
    projectsImages.eew_lang_bias,
  ],
  additionalRessources: [
    {
      content: {
        fr: "Rapport de stage",
        en: "Internship report",
      },
      link: documents.eew_internship_report,
    },
    {
      content: {
        fr: "Rapport d'activité",
        en: "Activity report",
      },
      link: documents.eew_activity_report,
    }
  ]
};
